In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
db = pd.read_csv("Bank Customer Churn Prediction.csv")

In [3]:
db.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# data info
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  int64
 1   credit_score      10000 non-null  int64
 2   country           10000 non-null  object
 3   gender            10000 non-null  object
 4   age               10000 non-null  int64
 5   tenure            10000 non-null  int64
 6   balance           10000 non-null  float64
 7   products_number   10000 non-null  int64
 8   credit_card       10000 non-null  int64
 9   active_member     10000 non-null  int64
 10  estimated_salary  10000 non-null  float64
 11  churn             10000 non-null  int64
dtypes: float64(2), int64(8), object(2)
memory usage: 937.6+ KB

In [5]:
# check null values
db.isnull().sum()

customer_id         0
credit_score        0
country             0
gender              0
age                 0
tenure              0
balance             0
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

In [6]:
# check duplicated values
db.duplicated().sum()

np.int64(0)

In [7]:
# check unique value
db["country"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [8]:
# check unique values
db["gender"].unique()

array(['Female', 'Male'], dtype=object)

In [9]:
# data described
db.describe()

,customer_id,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [10]:
# drop extra feature
db.drop("customer_id" , axis = 1 , inplace = True)

In [11]:
# assign x and y features
# x = independent feature
# y = dependent feature
x = db.drop("churn" , axis = 1)
y = db["churn"]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# split x and y into train test 
X_train , X_test , y_train , y_test = train_test_split(x , y , test_size = 0.3 , random_state = 42)

In [14]:
cat_cols = x.select_dtypes(include=['object']).columns
num_cols = x.select_dtypes(include=['int64', 'float64']).columns

In [15]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='first', sparse_output=False , handle_unknown = 'ignore')

X_train_cat = encoder.fit_transform(X_train[cat_cols])
X_test_cat  = encoder.transform(X_test[cat_cols])

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_num = scaler.fit_transform(X_train[num_cols])
X_test_num  = scaler.transform(X_test[num_cols])

In [17]:
X_train_final = np.hstack((X_train_cat, X_train_num))

In [18]:
X_test_final  = np.hstack((X_test_cat, X_test_num))

In [19]:
from tensorflow import keras 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import layers, activations

In [30]:
model = Sequential([
        Dense(20 , activation = 'relu' , input_dim = X_train_final.shape[1]),
        Dense(10 , activation = 'relu'),
        Dense(5  , activation = 'relu'),
        Dense(1  , activation = 'sigmoid')
])

In [31]:
model.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [32]:
history = model.fit(X_train_final , y_train , epochs = 100 , batch_size = 10 , validation_split = 0.20 , verbose = 1)

Epoch 1/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7989 - loss: 0.4562 - val_accuracy: 0.8100 - val_loss: 0.4234
Epoch 2/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8180 - loss: 0.4133 - val_accuracy: 0.8221 - val_loss: 0.4036
Epoch 3/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8345 - loss: 0.3887 - val_accuracy: 0.8350 - val_loss: 0.3854
Epoch 4/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8438 - loss: 0.3717 - val_accuracy: 0.8350 - val_loss: 0.3796
Epoch 5/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8520 - loss: 0.3588 - val_accuracy: 0.8457 - val_loss: 0.3714
Epoch 6/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8577 - loss: 0.3536 - val_accuracy: 0.8471 - val_loss: 0.3668
Epoch 7/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8579 - loss: 0.3477 - val_accuracy: 0.8500 - val_loss: 0.3590
Epoch 8/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8614 - loss: 0.3423 - val_accuracy: 0.8543 - val_loss: 0.3541
Epoch 9/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8614 - loss: 0.3399 - val_accuracy: 0.8514 - val_loss: 0.3546
Epoch 10/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8616 - loss: 0.3369 - val_accuracy: 0.8479 - val_loss: 0.3539
Epoch 11/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8625 - loss: 0.3358 - val_accuracy: 0.8543 - val_loss: 0.3628
Epoch 12/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8616 - loss: 0.3336 - val_accuracy: 0.8550 - val_loss: 0.3482
Epoch 13/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8634 - loss: 0.3323 - val_accuracy: 0.8514 - val_loss: 0.3503
Epoch 14/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8639 - loss: 0.3317 - val_accuracy: 0.8521 - val_loss: 0.3533
Epoch 15/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8668 - loss: 0.3302 - val_accuracy: 0.8564 - val_loss: 0.3495
Epoch 16/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8621 - loss: 0.3299 - val_accuracy: 0.8550 - val_loss: 0.3526
Epoch 17/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8627 - loss: 0.3279 - val_accuracy: 0.8507 - val_loss: 0.3473
Epoch 18/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8630 - loss: 0.3281 - val_accuracy: 0.8536 - val_loss: 0.3485
Epoch 19/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8629 - loss: 0.3272 - val_accuracy: 0.8586 - val_loss: 0.3488
Epoch 20/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8662 - loss: 0.3261 - val_accuracy: 0.8536 - val_loss: 0.3490
Epoch 21/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8641 - loss: 0.3251 - val_accuracy: 0.8543 - val_loss: 0.3493
Epoch 22/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.8664 - loss: 0.3242 - val_accuracy: 0.8557 - val_loss: 0.3486
Epoch 23/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8664 - loss: 0.3242 - val_accuracy: 0.8571 - val_loss: 0.3527
Epoch 24/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8673 - loss: 0.3236 - val_accuracy: 0.8557 - val_loss: 0.3507
Epoch 25/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8657 - loss: 0.3220 - val_accuracy: 0.8514 - val_loss: 0.3579
Epoch 26/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8668 - loss: 0.3222 - val_accuracy: 0.8571 - val_loss: 0.3581
Epoch 27/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8682 - loss: 0.3209 - val_accuracy: 0.8486 - val_loss: 0.3552
Epoch 28/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8668 - loss: 0.3204 - val_accuracy: 0.8529 - val_loss: 0.3513
Epoch 29/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8700 - loss: 0.3186 - val_accuracy: 0.8529 - val_loss: 0.3609
Epoch 30/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8686 - loss: 0.3198 - val_accuracy: 0.8521 - val_loss: 0.3542
Epoch 31/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8670 - loss: 0.3191 - val_accuracy: 0.8514 - val_loss: 0.3539
Epoch 32/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8700 - loss: 0.3183 - val_accuracy: 0.8557 - val_loss: 0.3570
Epoch 33/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8687 - loss: 0.3167 - val_accuracy: 0.8536 - val_loss: 0.3555
Epoch 34/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8704 - loss: 0.3161 - val_accuracy: 0.8557 - val_loss: 0.3537
Epoch 35/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8673 - loss: 0.3163 - val_accuracy: 0.8557 - val_loss: 0.3671
Epoch 36/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8682 - loss: 0.3155 - val_accuracy: 0.8536 - val_loss: 0.3553
Epoch 37/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8696 - loss: 0.3138 - val_accuracy: 0.8593 - val_loss: 0.3638
Epoch 38/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8693 - loss: 0.3144 - val_accuracy: 0.8536 - val_loss: 0.3543
Epoch 39/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.8730 - loss: 0.3130 - val_accuracy: 0.8464 - val_loss: 0.3566
Epoch 40/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.8727 - loss: 0.3133 - val_accuracy: 0.8543 - val_loss: 0.3620
Epoch 41/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8712 - loss: 0.3118 - val_accuracy: 0.8500 - val_loss: 0.3573
Epoch 42/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8729 - loss: 0.3106 - val_accuracy: 0.8521 - val_loss: 0.3593
Epoch 43/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8732 - loss: 0.3106 - val_accuracy: 0.8514 - val_loss: 0.3623
Epoch 44/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8754 - loss: 0.3103 - val_accuracy: 0.8493 - val_loss: 0.3580
Epoch 45/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8746 - loss: 0.3117 - val_accuracy: 0.8571 - val_loss: 0.3619
Epoch 46/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8752 - loss: 0.3086 - val_accuracy: 0.8457 - val_loss: 0.3605
Epoch 47/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8721 - loss: 0.3091 - val_accuracy: 0.8507 - val_loss: 0.3606
Epoch 48/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8727 - loss: 0.3094 - val_accuracy: 0.8614 - val_loss: 0.3593
Epoch 49/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.8734 - loss: 0.3081 - val_accuracy: 0.8507 - val_loss: 0.3575
Epoch 50/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8723 - loss: 0.3076 - val_accuracy: 0.8500 - val_loss: 0.3610
Epoch 51/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8732 - loss: 0.3087 - val_accuracy: 0.8557 - val_loss: 0.3589
Epoch 52/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8734 - loss: 0.3067 - val_accuracy: 0.8536 - val_loss: 0.3606
Epoch 53/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8750 - loss: 0.3063 - val_accuracy: 0.8607 - val_loss: 0.3652
Epoch 54/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8745 - loss: 0.3061 - val_accuracy: 0.8550 - val_loss: 0.3616
Epoch 55/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8761 - loss: 0.3051 - val_accuracy: 0.8543 - val_loss: 0.3629
Epoch 56/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8729 - loss: 0.3058 - val_accuracy: 0.8529 - val_loss: 0.3684
Epoch 57/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8730 - loss: 0.3046 - val_accuracy: 0.8529 - val_loss: 0.3642
Epoch 58/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8745 - loss: 0.3045 - val_accuracy: 0.8571 - val_loss: 0.3647
Epoch 59/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8764 - loss: 0.3046 - val_accuracy: 0.8557 - val_loss: 0.3600
Epoch 60/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8755 - loss: 0.3036 - val_accuracy: 0.8550 - val_loss: 0.3649
Epoch 61/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8768 - loss: 0.3037 - val_accuracy: 0.8557 - val_loss: 0.3648
Epoch 62/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8745 - loss: 0.3024 - val_accuracy: 0.8557 - val_loss: 0.3610
Epoch 63/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8734 - loss: 0.3033 - val_accuracy: 0.8486 - val_loss: 0.3596
Epoch 64/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8761 - loss: 0.3031 - val_accuracy: 0.8571 - val_loss: 0.3699
Epoch 65/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8727 - loss: 0.3029 - val_accuracy: 0.8507 - val_loss: 0.3645
Epoch 66/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8741 - loss: 0.3024 - val_accuracy: 0.8536 - val_loss: 0.3631
Epoch 67/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8764 - loss: 0.3014 - val_accuracy: 0.8479 - val_loss: 0.3610
Epoch 68/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8736 - loss: 0.3017 - val_accuracy: 0.8521 - val_loss: 0.3636
Epoch 69/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8771 - loss: 0.3008 - val_accuracy: 0.8521 - val_loss: 0.3694
Epoch 70/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8752 - loss: 0.3012 - val_accuracy: 0.8471 - val_loss: 0.3644
Epoch 71/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8752 - loss: 0.3016 - val_accuracy: 0.8550 - val_loss: 0.3617
Epoch 72/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8766 - loss: 0.3004 - val_accuracy: 0.8493 - val_loss: 0.3649
Epoch 73/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8759 - loss: 0.3000 - val_accuracy: 0.8500 - val_loss: 0.3665
Epoch 74/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8752 - loss: 0.3002 - val_accuracy: 0.8543 - val_loss: 0.3691
Epoch 75/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8741 - loss: 0.2986 - val_accuracy: 0.8471 - val_loss: 0.3768
Epoch 76/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8786 - loss: 0.3002 - val_accuracy: 0.8507 - val_loss: 0.3737
Epoch 77/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8780 - loss: 0.2999 - val_accuracy: 0.8450 - val_loss: 0.3671
Epoch 78/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.8779 - loss: 0.2987 - val_accuracy: 0.8521 - val_loss: 0.3661
Epoch 79/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8752 - loss: 0.2986 - val_accuracy: 0.8521 - val_loss: 0.3653
Epoch 80/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8766 - loss: 0.2972 - val_accuracy: 0.8514 - val_loss: 0.3661
Epoch 81/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8761 - loss: 0.2992 - val_accuracy: 0.8514 - val_loss: 0.3652
Epoch 82/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8804 - loss: 0.2974 - val_accuracy: 0.8529 - val_loss: 0.3650
Epoch 83/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8779 - loss: 0.2968 - val_accuracy: 0.8486 - val_loss: 0.3702
Epoch 84/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8789 - loss: 0.2949 - val_accuracy: 0.8507 - val_loss: 0.3641
Epoch 85/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8755 - loss: 0.2965 - val_accuracy: 0.8536 - val_loss: 0.3696
Epoch 86/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8788 - loss: 0.2948 - val_accuracy: 0.8507 - val_loss: 0.3796
Epoch 87/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8779 - loss: 0.2961 - val_accuracy: 0.8521 - val_loss: 0.3731
Epoch 88/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8784 - loss: 0.2960 - val_accuracy: 0.8507 - val_loss: 0.3650
Epoch 89/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8780 - loss: 0.2966 - val_accuracy: 0.8500 - val_loss: 0.3691
Epoch 90/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8779 - loss: 0.2931 - val_accuracy: 0.8464 - val_loss: 0.3669
Epoch 91/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8764 - loss: 0.2964 - val_accuracy: 0.8493 - val_loss: 0.3693
Epoch 92/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8796 - loss: 0.2931 - val_accuracy: 0.8479 - val_loss: 0.3731
Epoch 93/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8763 - loss: 0.2952 - val_accuracy: 0.8479 - val_loss: 0.3869
Epoch 94/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8784 - loss: 0.2958 - val_accuracy: 0.8514 - val_loss: 0.3684
Epoch 95/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8759 - loss: 0.2958 - val_accuracy: 0.8443 - val_loss: 0.3865
Epoch 96/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8786 - loss: 0.2951 - val_accuracy: 0.8471 - val_loss: 0.3785
Epoch 97/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8782 - loss: 0.2913 - val_accuracy: 0.8479 - val_loss: 0.3710
Epoch 98/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8779 - loss: 0.2938 - val_accuracy: 0.8486 - val_loss: 0.3710
Epoch 99/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8779 - loss: 0.2949 - val_accuracy: 0.8479 - val_loss: 0.3775
Epoch 100/100
560/560 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8805 - loss: 0.2941 - val_accuracy: 0.8457 - val_loss: 0.3729

In [38]:
loss , acc = model.evaluate(X_test_final , y_test , verbose = 0)

In [39]:
print(acc)
print(loss)

0.8533333539962769
0.35827505588531494

In [40]:
y_pred = model.predict(X_test_final)

print(y_test[:5])
# [1, 0, 1, 0, 1]

print(y_pred[:5])
# [0.87, 0.12, 0.65, 0.31, 0.91]

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
6252    0
4684    0
1731    0
4742    0
4521    0
Name: churn, dtype: int64
[[0.01903701]
 [0.00656919]
 [0.11915576]
 [0.050103  ]
 [0.08467762]]

In [42]:
from sklearn.metrics import precision_score , accuracy_score , recall_score
from sklearn.metrics import classification_report

y_pred = (model.predict(X_test_final) > 0.5).astype(int)

print(f"Accuracy        : {accuracy_score(y_test , y_pred)}")
print(f"Precision       : {precision_score(y_test , y_pred)}")
print(f"Recall          : {recall_score(y_test , y_pred)}")
print(f"Classification  : {classification_report(y_test , y_pred)}")

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Accuracy        : 0.8533333333333334
Precision       : 0.6643835616438356
Recall          : 0.4982876712328767
Classification  :               precision    recall  f1-score   support

           0       0.89      0.94      0.91      2416
           1       0.66      0.50      0.57       584

    accuracy                           0.85      3000
   macro avg       0.78      0.72      0.74      3000
weighted avg       0.84      0.85      0.85      3000